### ISSUE TITLE
Status update calls for products

### ISSUE THREAD

**Issue by goosecoid** [databrokerglobal/dxc#69]
1. Products model don't have the DID property -> replace UUID with DID
2. Make a repeating task to call an endpoint on the DXS for status updates. An easy way to achieve this is through time.NewTicker method in the golang library, more info here: [](https://stackoverflow.com/questions/16466320/is-there-a-way-to-do-repetitive-tasks-at-intervals
)
3. Store each challenge in the database

**Comment by woodyjon** [comment]
refer to process here: https://www.notion.so/settlemint/Databroker-authentication-5eee04b6739d4c9fae0d037d05663e47
