### ISSUE TITLE
Generate DXC ARM Docker Builds for Phoenix Contact

### ISSUE THREAD

**Issue by viktor-settlemint** [databrokerglobal/dxc#718]
Connect DXC to Phoenix Contact PLC's device.

**Comment by ashlesh-settlemint** [comment]
DXC with arm32v7 arch is ready to be tested on PLC.
https://hub.docker.com/repository/docker/ashlesh/dxc

Things to be tested:

1. The whole buyer-seller flow should work from the dxc hosted on PLC. (Should have data storage mapping from the memory card of PLC).
2. After restarting the PLC, dxc should be up and running.
