### ISSUE TITLE
Buyers are able to use old data product link to access the data without extending their purchase

### ISSUE THREAD

**Issue by ashlesh-settlemint** [databrokerglobal/dxc#809]
DXC and DXS generate a new challenge string every 10 mins. The download link has `DXC_PRODUCT_KEY` which is basically a jwt token that contains the latest challenge string.

AC: 
1. update dxc's `CheckDXCProductKey` middleware to check the validity of the challenge key. 
2. Throw exception if the challenge string is expired, else provide access to the buyer.

**Comment by viktor-settlemint** [comment]
@ashlesh-settlemint same for this one? Can we ask Niklhil?

**Comment by ashlesh-settlemint** [comment]
@viktor-settlemint, yes if he has bandwidth.

**Comment by brillnik** [comment]
ok i can help but explain a bit

**Comment by viktor-settlemint** [comment]
@brillnik where do we stand on this?

**Comment by brillnik** [comment]
I haven't started working on it i was working on the work flow

**Comment by viktor-settlemint** [comment]
@sridharsettlemint @ashlesh-settlemint
