### ISSUE TITLE
Mapping datasource on data product page shows deleted datasources.

### ISSUE THREAD

**Issue by ashlesh-settlemint** [databrokerglobal/dxc#813]
Mapping datasource on data product page shows deleted datasources. When datasource is deleted from dxc, it soft deletes it. 

Slack link for issue -
https://settlemint.slack.com/archives/C02NT7F151Q/p1639636682080000

AC: 
1. Find out which way would be better suitable - hard delete of datasource or filter active datasource.
2. Make the respective changes required in dxc/dxs

**Comment by viktor-settlemint** [comment]
@ashlesh-settlemint who is working on this issue currently?

**Comment by ashlesh-settlemint** [comment]
@viktor-settlemint We have asked Sridhar to work on it, but said he would like to work on one api for dxs first.

**Comment by viktor-settlemint** [comment]
@sridharsettlemint can you link your PR to it please?
