### ISSUE TITLE
Create a workflow for DXC

### ISSUE THREAD

**Issue by viktor-settlemint** [databrokerglobal/dxc#823]
We need to create a workflow everytime we push an PR and it is merged into master (https://github.com/databrokerglobal/dxc/actions/new)
We need to first define all the tests that need to go through and what should be the end task (deploy and create a new docker image)

@ashlesh-settlemint @brillnik could we list here below a basic flow we would like? Should it create a new docker image at the end? and update all the running DXCs?

**Comment by brillnik** [comment]
Ya sure

**Comment by brillnik** [comment]
> @brillnik could you also look at the tests which are running when you build an image? and which ones who be required according to you?

@viktor-settlemint its all the basic test are running it will be required according to me

**Comment by viktor-settlemint** [comment]
@brillnik I do not understand. 
Everytime we build an image how can we test that the DXC image works properly?
Before building it, can't we test if it runs properly? If we can query an API etc?
I would like to see if the thing work basically.

**Comment by brillnik** [comment]
@viktor-settlemint we need to link the databroker docker hub to github and setup the auto builds for that

**Comment by brillnik** [comment]
> @viktor-settlemint we need to link the databroker docker hub to github and setup the auto builds
